---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: devops
spec:
  encryptedData:
    my-config-file.yml: AgBHpWqKfM/3aplOEA2Jn78sD8yGw8TGN7pTdNwFpZ2ia+0MfmNR5eUXWnpvgGYZTNc8IV05I7p1MIklGZcItlZ2e/TkttC/eVM31hT5XlXRqvTYk0WdWPaNRR7G3kD3WrFKEPbOchPunZdq7EsdyI1+sEchY9SUO5pa/wufEXAjDBugag/C8U5ZLZE0TYdjhSpHs9G105e4rS7qUk6c/ZgiISbhEGVX2Wjnq7WaH/WqAKnoYWP6yiE/798BfxpYhTT54/Qc9uKRAbGW25zBODPVznmYr1qdcG7rx3XXVn0YI2saaDFXLIh9Jzt57Nlgxbmc9Q34+XPcb1hZAlM6kmkh+mGrWWIKOq8jUsSCK7p10UpE9nKB1+ndos/2VON66kdk6v9k7lOXid1c2qkvVSj3sSumLU2RXi0NYGxEXpdbJwzuINLsmdK50tbZ3651yIUZ/k4Rn3tL73aqC5ji4U83n9vUFIz22Ca5mr1bOcjXAb+VgZb1ADtiBza+Gy0w/su6QAJUwZvMgOtsFhkx9zyjqzAockJgn5gK3I8BP6iMBlRklmi0Kj8lRYVngQ3OMA+HmcboGYeJYBO7iyZSE1PNP3TWP+pFbh0N/jZlDtxgsug6CONM7psMEfXe9R45EqUwnPWPOZps8bADZgmDG6X0wEhl78kVZ1D70jBPH4vZ99ebFg8duVwF4uud6QmMC4+dcGAwxOnchAr7HuezGi/A0tT4SBfY431jkdlCuA6s2D1O3rq/FmhEx7MlEyVyvchNDfwtYJzG+ycNiNzMx+l/pOsxkd0EdsPOz5hs5kA4gCnzpB60Bc+9o13KZsrFUyMxrE7AJR3pka4=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: devops
